config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    resources :lessons
  end
  resources :users, only: [:index, :edit, :show, :update]
  root 'courses#welcome' # root 'courses#index'
  get 'courses/index'
  get 'welcome', to: 'courses#welcome'
  get 'activity', to: 'courses#activity'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable
        
  after_create :assign_default_role
  
  validate :must_have_a_role, on: :update
  
  has_many :courses
  
  extend FriendlyId
  friendly_id :email, use: :slugged
         
  def to_s
    email
  end
  
  def username
    self.email.split(/@/).first
  end

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:teacher)
      self.add_role(:student)
    else
      self.add_role(:student) if self.roles.blank?
      self.add_role(:teacher)
    end
  end
  
  def online?
    updated_at > 2.minutes.ago
  end
  
  private
  
  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "Error! The user must have at least one role.")
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
      # @users = User.all.order(created_at: :desc)
      
      # for using with ransack
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
  
    # GET /users/1 or /users/1.json
  def show
  end
  
    # GET /users/1/edit
  def edit
    authorize @user
  end
  
  # PATCH/PUT /users/1 or /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Yay! The user has been successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "The user has been successfully deleted." }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit({role_ids: []})
    end
    
end

app/views/users/_user.html.haml
.col
  .card.h-100.mt-3
    .card-header
      .fa.fa-user-circle-o
      - if user.online?
        .text-success.fa.fa-circle
      - else
        .text-danger.fa.fa-circle
      = link_to user.username, user_path(user)
    .card-body
    .card-footer
      .fa.fa-clock-o
      Signed up
      = time_ago_in_words(user.created_at)
      ago
    .card-footer
      %b= 'sign_in_count'.humanize+ ":"
      = user.sign_in_count
      .row
      %b= 'current_sign_in_at'.humanize+ ":"
      = user.current_sign_in_at
      .row
      %b= 'last_sign_in_at'.humanize+ ":"
      = user.last_sign_in_at
      .row
      %b= 'current_sign_in_ip'.humanize+ ":"
      = user.current_sign_in_ip
      .row
      %b= 'last_sign_in_ip'.humanize+ ":"
      = user.last_sign_in_ip
    .card-footer
      Email confirmed?
      - if user.confirmed_at.present?
        .badge.bg-success Yes
      - else
        .badge.bg-danger No
    .card-footer
      - user.roles.each do |role|
        .badge.bg-secondary
          = role.name
      - if policy(user).edit?
        = link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning'
    //   = link_to 'Learn more', user, class: 'btn btn-sm btn-primary'
    //   = link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-warning'
    //   = link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure you want to delete it?' }, class: 'btn btn-sm btn-danger'

app/views/users/edit.html.haml
.card
  .card-header
    Editing roles for
    = @user.username
  .card-body
    .p Update the user's role
    = simple_form_for @user do |f|
      = f.collection_check_boxes :role_ids, Role.all, :id, :name
      = f.error :roles, class: 'text-danger'
      %hr
      = f.button :submit, class: "btn btn-success"
  .card-footer
    = link_to 'Cancel', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
%h3
  .text-center
    Number of registered users
    .badge.bg-secondary
      = @users.count
.row.row-cols-1.row-cols-md-2.row-cols-lg-3.g-4
  - @users.each do |user|
    = render 'users/user', user: user
.row.mt-4
  = search_form_for @q do |f|
    = f.search_field :email_cont, placeholder: 'email'
    = f.search_field :sign_in_count_eq, placeholder: 'sign in count'
    = f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count'
    = f.submit
  .ml-2
    = link_to 'refresh', users_path

%table.table.table-bordered
  %thead
    %tr
      %th id
      %th= sort_link(@q, :email)
      %th created_at
      %th= 'sign_in_count'.humanize
      %th= 'current_sign_in_at'.humanize
      %th= 'last_sign_in_at'.humanize
      %th= 'current_sign_in_ip'.humanize
      %th= 'last_sign_in_ip'.humanize
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.username
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip

app/views/users/show.html.haml
%p
= link_to 'Users', users_path
\/
= link_to @user.username, user_path(@user)

%p
= render 'users/user', user: @user