config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    resources :lessons
  end
  resources :users, only: [:index, :edit, :show, :update]
  root 'courses#welcome' # root 'courses#index'
  get 'courses/index'
  get 'welcome', to: 'courses#welcome'
  get 'activity', to: 'courses#activity'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        © 
        = Time.now.year
        Coursella
        .row
        .fa.fa-envelope
        = mail_to 'email@coursella.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on Coursella', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.px-3
  %a.navbar-brand{:href => "/"} Coursella
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-book
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-user-circle
            Users
      = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
        .input-group
          = f.search_field :title_or_short_description_cont, class: 'form-control', placeholder: 'Search', :autocomplete => :off
          %span.input-group-append
            %button.btn.btn-outline-success.mx-2{:type => "submit"}
              %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            Add a new course
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(activity_path)}"}
          = link_to activity_path, class: 'nav-link' do
            .fa.fa-exchange
            Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.username
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "px-3 alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      = content_tag :div, msg, :id => "flash_#{name}"
      // %button.btn-close{"aria-label" => "Close", type: "button", "aria-hidden" => "true", "data-dismiss" => "alert"}
      // %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Courses
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      = yield
    = render 'layouts/footer'